#Step-1
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion #output
  source_url: https://github.com/Satya-bit/datasets/raw/refs/heads/main/summarizer-data.zip #INPUT YOUR SOURCE URL
  local_data_file: artifacts/data_ingestion/data.zip
  unzip dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
